apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-cluster
  region: us-east-1
managedNodeGroups:
  - name: nodegroup
    instanceType: t2.medium
    minSize: 1
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      publicKeyName: udacity