apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-cluster
  region: us-east-1
managedNodeGroups:
  - name: nodegroup
    instanceType: t2.micro
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      publicKeyName: udacity